### ISSUE TITLE
Remove **Requires: python-setuptools** from spec file

### ISSUE THREAD

**Issue by chkumar246** [redhat-openstack/easyfix#10]
python-setuptools is required during %build step during rpm package building process.
So, it should be used as BuilRequires: python-setuptools in spec file.
In lots of RDO packages, python-setuptools is used as a Requires that's needs to be remove.

## What to improve:

1. Clone os-apply-config spec file git clone https://github.com/rdo-packages/os-apply-config-distgit
2. Go to os-apply-config-distgit and open os-apply-config.spec in editor.
3. You can find Requires:	python-setuptools in spec file.
4. We need to remove this line "Requires:	python-setuptools" from spec file.
5. Once done! Make changes, add and commit it and send a Gerrit Review.
6. Please cross [checklist](https://github.com/redhat-openstack/easyfix#checklist-for-sending-your-first-rdo-gerrit-review)
   before sending Gerrit Review.

## Example Spec containing the above fix:

1. [tempest-horizon](https://github.com/rdo-packages/tempest-horizon-distgit)

## Below is the list of packages which need same fixes:

- [x] [os-apply-config](https://github.com/rdo-packages/os-apply-config-distgit)
- [x] [os-refresh-config](https://github.com/rdo-packages/os-refresh-config-distgit)
- [x] [os-net-config-distgit](https://github.com/rdo-packages/os-net-config-distgit)
- [x] [os-collect-config](https://github.com/rdo-packages/os-collect-config-distgit)
- [x] [kolla](https://github.com/rdo-packages/kolla-distgit)
- [x] [tripleo-validations](https://github.com/rdo-packages/tripleo-validations-distgit)

## Mentors

1. chandankumar

**Comment by snecklifter** [comment]
https://review.rdoproject.org/r/7981
https://review.rdoproject.org/r/7982
https://review.rdoproject.org/r/7983 <--- os-cloud-config abandoned as retired upstream @chkumar246 
https://review.rdoproject.org/r/7984
https://review.rdoproject.org/r/7985
https://review.rdoproject.org/r/7986

**Comment by snecklifter** [comment]
I suspect there are more, will check before closing this.

**Comment by snecklifter** [comment]
Have checked, no more occurrences.

**Comment by apevec** [comment]
Just a note that setuptools could be a hidden runtime dep, like we discovered in Packstack:
https://review.rdoproject.org/r/9090
