### ISSUE TITLE
Remove **BuildRequires/Requires: python-coverage** from spec file

### ISSUE THREAD

**Issue by chkumar246** [redhat-openstack/easyfix#11]
python-coverage is used to generate test coverage report for any project. During
RPM building process, we run tests only and donot generate coverage report.
In RDO Packages, at most places python-coverage is used as BuildRequires or Requires.

## What to improve:

1. Clone tripleo-validations-distgit spec file git clone https://github.com/rdo-packages/tripleo-validations-distgit
2. Go to tripleo-validations-distgit and open  openstack-tripleo-validations.spec in editor.
3. You can find Requires:	python-coverage OR/AND BuildRequires: python-coverage in spec file.
4. We need to remove those lines from spec file.
5. Once done! Make changes, add and commit it and send a Gerrit Review.
6. Please cross [checklist](https://github.com/redhat-openstack/easyfix#checklist-for-sending-your-first-rdo-gerrit-review)
   before sending Gerrit Review.

## Example Spec containing the above fix:

1. [python-os-traits](https://github.com/rdo-packages/os-traits-distgit)

## Below is the list of packages which need same fixes:

- [x] [tripleo-validations](https://github.com/rdo-packages/tripleo-validations-distgit)
- [x] [networking-fujitsu](https://github.com/rdo-packages/networking-fujitsu-distgit)
- [x] [oslo-serialization](https://github.com/rdo-packages/oslo-serialization-distgit)
- [x] [keystoneclient](https://github.com/rdo-packages/keystoneclient-distgit)
- [x] [osc-lib](https://github.com/rdo-packages/osc-lib-distgit)
- [x] [shaker](https://github.com/rdo-packages/shaker-distgit)
- [x] [mox3](https://github.com/rdo-packages/mox3-distgit)
- [x] [tempest](https://github.com/rdo-packages/tempest-distgit)
- [x] [mistral-dashboard](https://github.com/rdo-packages/mistral-dashboard-distgit)
- [x] [novajoin](https://github.com/rdo-packages/novajoin-distgit)
- [ ] [cinder](https://github.com/rdo-packages/cinder-distgit)
- [ ] [congressclient](https://github.com/rdo-packages/congressclient-distgit)
- [ ] [congress](https://github.com/rdo-packages/congress-distgit)
- [ ] [cursive](https://github.com/rdo-packages/cursive-distgit)
- [ ] [heat-translator](https://github.com/rdo-packages/heat-translator-distgit)
- [ ] [horizon](https://github.com/rdo-packages/horizon-distgit)
- [ ] [magnum](https://github.com/rdo-packages/magnum-distgit)
- [ ] [microversion-parse](https://github.com/rdo-packages/microversion-parse-distgit)
- [ ] [murano-agent](https://github.com/rdo-packages/murano-agent-distgit)
- [ ] [networking-bagpipe](https://github.com/rdo-packages/networking-bagpipe-distgit)
- [ ] [networking-bgvpn](https://github.com/rdo-packages/networking-bgpvpn-distgit)
- [ ] [networking-l2gw](https://github.com/rdo-packages/networking-l2gw-distgit)
- [ ] [octavia](https://github.com/rdo-packages/octavia-distgit)
- [ ] [openstackclient](https://github.com/rdo-packages/openstackclient-distgit)
- [ ] [openstack-sdk](https://github.com/rdo-packages/openstacksdk-distgit)
- [ ] [os-faults](https://github.com/rdo-packages/os-faults-distgit)
- [ ] [oslo-concurrency](https://github.com/rdo-packages/oslo-concurrency-distgit)
- [ ] [oslo-context](https://github.com/rdo-packages/oslo-context-distgit)
- [ ] [oslo-reports](https://github.com/rdo-packages/oslo-reports-distgit)
- [ ] [sahara-tests](https://github.com/rdo-packages/sahara-tests-distgit)
- [ ] [vitrageclient](https://github.com/rdo-packages/vitrageclient-distgit)
- [ ] [watchr](https://github.com/rdo-packages/watcher-distgit)

## Mentors

1. chandankumar

**Comment by OGtrilliams** [comment]
test builds failed for keystoneclient & tripleo-validations, but mistrial-dashboard worked: 

https://review.rdoproject.org/r/#/c/7742/
https://review.rdoproject.org/r/#/c/7747/

**Comment by mrunge** [comment]
IMO, coverage should not be removed from horizon spec file. Tests are not run there during package build (different issue), but if you're running the tests, coverage gives a bit more detail.

**Comment by snecklifter** [comment]
@chkumar246 can you discuss with other cores please as I'm just doing the work. Cheers.

**Comment by amoralej** [comment]
My opinion on this is:

1. In packages not running tests with coverage in %check we can remove coverage as BuildRequires
2. coverage is optional when running unit tests manually so if a user wants to run tests with coverage, he must install python-coverage manually and run it. So i think python-coverage should not be Requires in -tests package as general rule.

**Comment by javierpena** [comment]
Agreed with amoralej's comment. If coverage is not being actively used in %check, it doesn't make any sense to keep it as a build requirement (because it's not).
