### ISSUE TITLE
[packstack] Install dashboard plugins for projects deployed by packstack

### ISSUE THREAD

**Issue by amoralej** [redhat-openstack/easyfix#14]
**What to improve**

Packstack does not install horizon plugins when deploying services. For example, when enabling magnum installation by using CONFIG_MAGNUM_INSTALL option in answer file, magnum services are installed and configured but package openstack-magnum-ui is not installed.

Currently, following services have dashboard plugins in RDO which should be installed as part of horizon deployment when enabled:

|project    |horizon plugin package|
|------------|----------------------------|
|magnum | openstack-magnum-ui|
|sahara | openstack-sahara-ui|
|ironic | openstack-ironic-ui|
|trove | openstack-trove-ui|
|lbaas | openstack-neutron-lbaas-ui|

**Hint about implementation**

Packstack provides a [puppet manifest](https://github.com/openstack/packstack/blob/master/packstack/puppet/modules/packstack/manifests/horizon.pp) to install and configure horizon using puppet-horizon . That manifest should check if services are enabled in hiera, as for example using `hiera('CONFIG_MAGNUM_INSTALL') ` and if it's enabled make sure the package openstack-magnum-ui is installed.

**Contributing**

Packstack is an OpenStack project and follows the peer-review process based on reviews in [OpenStack gerrit](http://review.openstack.org). Instructions about how to contribute to packstack can be found in [the wiki page](https://wiki.openstack.org/wiki/Packstack#Packstack_Development).

**Mentors**
- amoralej

- [X] neutron-lbaas-ui
- [X] magnum-ui
- [X] ironic-ui
- [x] trove-ui
- [x] sahara-ui

**Comment by OGtrilliams** [comment]
I will happily do all of these!

**Comment by OGtrilliams** [comment]
Would you mind pointing out an example for reference?

**Comment by amoralej** [comment]
Here you have an example used in openstackclient manifest to install manilaclient when CONFIG_MANILA_INSTALL is enabled:

https://github.com/openstack/packstack/blob/master/packstack/puppet/modules/packstack/manifests/openstackclient.pp#L9-L11

In this case you'd need something similar but for other services and package names, as shown in the issue description. It should go in https://github.com/openstack/packstack/blob/master/packstack/puppet/modules/packstack/manifests/horizon.pp

**Comment by OGtrilliams** [comment]
Awesome, thanks Alfredo. I was close but I was putting it in the wrong file. i tested all of these on Ocata- seems they all work OK.

neutron-lbaas-ui - https://review.openstack.org/488517
magnum-ui - https://review.openstack.org/488523
ironic-ui - https://review.openstack.org/488532
trove-ui - https://review.openstack.org/488536
sahara-ui - https://review.openstack.org/488558

**Comment by snecklifter** [comment]
Just waiting on Trove and Sahara now.

@OGtrilliams just a couple of minor nits on those commits I think...

**Comment by snecklifter** [comment]
@amoralej any more or are you happy to close this one?

**Comment by amoralej** [comment]
@OGtrilliams thanks for these patches, they will be included in packstack version in pike.
