### ISSUE TITLE
Script/Tool to update package list doc

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/easyfix#15]
In the docs we have a package list:

https://www.rdoproject.org/documentation/package-list/

It's probably out of date.

We need the following:

* A tool of some kind to generate the content for that page
* Documentation, probably linked from that page, on how to use it
* Perhaps two versions of the page - one for released (Ocata, in this case) and one for development (Pike, in this case), and instructions to generate each.

There was a mailing list thread back around the time that this page was last updated, with some instructions on how to generate the doc. That might be a good place to start.

**Comment by snecklifter** [comment]
Could I ask what the point of the list is?
Can we just point to:

http://mirror.centos.org/centos/7/cloud/x86_64/openstack-ocata/

?

**Comment by rbowen** [comment]
Yeah, you make a good point. I guess this doesn't offer any additional information.

**Comment by snecklifter** [comment]
Ok, have created PR to update doc to point to that:

https://github.com/redhat-openstack/website/pull/1027

**Comment by rbowen** [comment]
Merged. This issue is resolved, I believe.
