### ISSUE TITLE
Replace comments boxes with proper comment for openstack-sahara spec

### ISSUE THREAD

**Issue by chkumar246** [redhat-openstack/easyfix#17]
openstack-sahara spec file contains square boxed comment boxes. We need to
clean this up so that we can keep similar comment pattern across the rdo specs.

## What to improve:

* Clone openstack-sahara spec file using `git clone https://github.com/rdo-packages/sahara-distgit`
* Go to sahara-distgit and open openstack-sahara.spec file in editor.
* You can remove square brackets comment boxes in which some content is written.
* We need to replace this with `# <content>` at each places.
* Once done! Make changes, add and commit it and send a Gerrit Review.
* Please cross [checklist](https://github.com/redhat-openstack/easyfix#checklist-for-sending-your-first-rdo-gerrit-review)
   before sending Gerrit Review.

## Mentors

1. chandankumar

**Comment by snecklifter** [comment]
https://review.rdoproject.org/r/#/c/7980/

**Comment by chkumar246** [comment]
Closing, as it is already resolved.
