### ISSUE TITLE
Use %{?systemd_requires} instead of individual Requires for systemd scriptlets

### ISSUE THREAD

**Issue by javierpena** [redhat-openstack/easyfix#23]
There are several packages where the runtime systemd requirements to run the post/preun/etc scriptlets are expressed as:

Requires(post):   systemd
Requires(preun):  systemd
Requires(postun): systemd

We can replace them with a single macro that does the same:

%{?systemd_requires}

One example of this can be found in https://github.com/rdo-packages/nova-distgit/blob/rpm-master/openstack-nova.spec#L116-L118, but there are other packages with the same issue.

**Comment by snecklifter** [comment]
@javierpena these are all done (I think!)

**Comment by snecklifter** [comment]
Done and dusted. :)
