### ISSUE TITLE
installing using pack stack on redhat error generates ( openstack-selinux-0.8.13-1.el7.noarch (openstack-queens)

### ISSUE THREAD

**Issue by haiderzia** [redhat-openstack/easyfix#25]
While installation openstack using packstack it create an error, the error is 

**192.168.40.128_controller.pp:                     [ ERROR ]
Applying Puppet manifests                         [ ERROR ]

ERROR : Error appeared during Puppet run: 192.168.40.128_controller.pp
Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install openstack-selinux' returned 1: Error: Package: openstack-selinux-0.8.13-1.el7.noarch (openstack-queens)
You will find full trace in log /var/tmp/packstack/20180629-125824-3SGsJm/manifests/192.168.40.128_controller.pp.log**

While checking  log file : /var/tmp/packstack/20180629-125824-3SGsJm/manifests/192.168.40.128_controller.pp.log

**Warning: /Stage[main]/Keystone::Deps/Anchor[keystone::service::end]: Skipping because of failed dependencies
Error: Failed to apply catalog: Insufficient credentials to authenticate**

**Comment by apevec** [comment]
This is not right channel for asking community support question, you can try http://ask.rdoproject.org (links to ask.openstack.org with rdo tag) or IRC.
