### ISSUE TITLE
Fix dates in blog post frontmatter

### ISSUE THREAD

**Issue by rbowen** [redhat-openstack/easyfix#8]
Date in blog post filename and in the metadata don't match.

See https://github.com/redhat-openstack/website/issues/976 for detailed description of this problem.

**Comment by Warlord77** [comment]
I am interested in picking up this issue

**Comment by rbowen** [comment]
Go for it. If you need any assistance at all, please let me know. You can contact me by email - rbowen@redhat.com - or on #RDO on Freenode IRC (rbowen).

The content for these blogs is in the directory source/blog/ when you have cloned the repo.

**Comment by rbowen** [comment]
I presume that someone fixed these and just didn't reference the ticket. These seem all resolved now.
